"""Add specialty and image_url to barbers

Revision ID: 675190b15658
Revises: bfeeac7083b9
Create Date: 2025-04-15 12:59:10.341154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675190b15658'
down_revision = 'bfeeac7083b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
