"""Add specialty and image_url to barbers

Revision ID: 9551865edc99
Revises: 675190b15658
Create Date: 2025-04-15 13:08:03.978100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9551865edc99'
down_revision = '675190b15658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
