"""Remove appointment_id from Review

Revision ID: 9a05ccb3d943
Revises: 076cd9ee6edd
Create Date: 2025-04-14 07:27:23.445509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a05ccb3d943'
down_revision = '076cd9ee6edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_appointment_id_appointments', type_='foreignkey')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('appointment_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_reviews_appointment_id_appointments', 'appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###
