"""new migration after reset

Revision ID: d9747e2b8194
Revises: e23290c0c0f1
Create Date: 2025-04-15 08:01:58.567788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9747e2b8194'
down_revision = 'e23290c0c0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reviews')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('barber_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_reviews_appointment_id_appointments'),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name='fk_reviews_barber_id_barbers'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_reviews_client_id_clients'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
