"""fixed models

Revision ID: e23290c0c0f1
Revises: fa061058567e
Create Date: 2025-04-14 08:23:32.277719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23290c0c0f1'
down_revision = 'fa061058567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_appointment_id_appointments'), 'appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_appointment_id_appointments'), type_='foreignkey')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
